# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 09:50
from __future__ import unicode_literals
from django.utils.text import slugify
from django.db import migrations


def add_slug_data(apps, schema_editor):
    Group = apps.get_model('datatable', 'Group')
    groups = Group.objects.all()
    title_slug_list = []
    title_list = []
    for group in groups:
        title_list.append(group.title)
        title_slug_list.append(slugify(group.title, allow_unicode=True))
    for i in range(len(title_list)):
        Group.objects.filter(title=title_list[i]).update(slug=title_slug_list[i])


def remove_slug_data(apps, schema_editor):
    Group = apps.get_model('datatable', 'Group')
    groups = Group.objects.all()
    title_slug_list = []
    title_list = []
    for group in groups:
        title_list.append(group.title)
        title_slug_list.append(slugify(group.title, allow_unicode=True))
    for i in title_slug_list:
        Group.objects.filter(title=title_list[i]).update(slug='')

class Migration(migrations.Migration):

    dependencies = [
        ('datatable', '0002_auto_20170527_1246'),
    ]

    operations = [
        migrations.RunPython(add_slug_data, remove_slug_data),
    ]
