# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datatable', '0004_auto_20170527_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=31, unique=True),
        ),
    ]
