# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datatable', '0005_auto_20170527_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='stud_id',
            field=models.PositiveIntegerField(),
        ),
    ]
