# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 16:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datatable', '0006_auto_20170527_1512'),
    ]

    operations = [
        migrations.RenameModel('Group', 'StudyGroup'),
        migrations.RenameField('Student', 'group', 'studygroup'),
    ]
