# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 16:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datatable', '0007_auto_20170530_1902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='stud_id',
        ),
    ]
